spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create          # drop and create table when application loaded. only in developing stage
    properties:
      hibernate:
        #show_sql: true         # print in console (System.out.println) -> use hibernate.SQL
        format_sql: true

logging.level:
  org.hibernate.SQL: debug    # leave as log
  #org.hibernate.type: trace  # To check parameter, it's beeter to use p6spy library.

